---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install chrony
  package:
    name:
      - chrony

- name: Enable chrony at boot
  service:
    name: "{{ service_name }}"
    enabled: yes

- name: Configure chrony to use Amazon Time Sync Service
  block:
    # ansible-lint complains that we have not set the mode for the two
    # replace tasks, but since we are at most modifying the file in
    # place it should not be necessary to do so.  Hence the noqa 209
    # for each of those tasks.
    - name: Comment out existing pool lines
      replace: # noqa 208
        path: "{{ config_file }}"
        regexp: ^(pool .*)
        replace: '# \1'
    - name: >
        Comment out existing server lines that do not correspond to the
        Amazon Time Sync Service
      replace: # noqa 208
        path: "{{ config_file }}"
        # The negative lookahead makes this regex match lines that
        # start with "server " but _do not_ look like "server
        # 169.254.169.123 prefer iburst", which is exactly what we
        # want.
        regexp: ^(server (?!169\.254\.169\.123 prefer iburst).*)
        replace: '# \1'
    - name: Add a server line for Amazon Time Sync Service
      blockinfile:
        block: |
          # Sync with Amazon Time Sync Service
          server 169.254.169.123 prefer iburst
        path: "{{ config_file }}"
  # AmazonLinux is already configured to use Amazon Time Sync Service
  when:
    - ansible_distribution != "Amazon"
