---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install chrony
  package:
    name:
      - chrony

- name: Enable chrony at boot
  service:
    name: "{{ service_name }}"
    enabled: yes

- name: Configure chrony to use Amazon Time Sync Service
  block:
    - name: Comment out existing pool lines
      replace:
        path: "{{ config_file }}"
        regexp: ^(pool .*)
        replace: '# \1'
    - name: >
        Comment out existing server lines that do not correspond to the
        Amazon Time Sync Service
      replace:
        path: "{{ config_file }}"
        # The negative lookahead makes this regex match lines that
        # start with "server " but _do not_ look like "server
        # 169.254.169.123 prefer iburst", which is exactly what we
        # want.
        regexp: ^(server (?!169\.254\.169\.123 prefer iburst).*)
        replace: '# \1'
    - name: Add a server line for Amazon Time Sync Service
      blockinfile:
        block: |
          # Sync with Amazon Time Sync Service
          server 169.254.169.123 prefer iburst
        path: "{{ config_file }}"
  # AmazonLinux is already configured to use Amazon Time Sync Service
  when:
    - ansible_distribution != "Amazon"
