---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install chrony
  package:
    name:
      - chrony

- name: Enable chrony at boot
  service:
    name: "{{ service_name }}"
    enabled: yes

- name: Configure chrony to use Amazon Time Sync Service
  block:
    - name: Comment out existing pool and server lines
      lineinfile:
        backrefs: yes
        line: '# \1'
        path: "{{ config_file }}"
        regexp: ^({{ item }}.*)
      loop:
        - pool
        - server
    - name: Add a server line for Amazon Time Sync Service
      lineinfile:
        line: server 169.254.169.123 prefer iburst
        path: "{{ config_file }}"
  # AmazonLinux is already configured to use Amazon Time Sync Service
  when:
    - ansible_distribution != "Amazon"
